# Generated by Django 4.1 on 2024-01-21 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 22, 37, 21, 972171, tzinfo=datetime.timezone.utc)),
        ),
    ]
